#!/usr/bin/env python3
"""Generate the Azure Pipelines YAML files from ado-pr-guard.sh and ../patterns.ere (single source).

  python3 gen.py                 write pipelines/*.yml
  python3 gen.py --check         exit 1 when pipelines/*.yml differ from what would be generated
  python3 gen.py --extract DIR   write each pipeline's bash steps to DIR (used by tests/)

pipelines/attribution-guard.yml (build validation) and pipelines/attribution-audit.yml (push audit)
go into each WORK repository (e.g. .azure-pipelines/); the first embeds the guard. The status and sweep pipelines run from a PROTECTED guard repository that is an import of
this repository, so they reference tools/attribution-guard/... paths directly.
"""
import pathlib
import re
import sys
import textwrap

here = pathlib.Path(__file__).resolve().parent
guard = (here / "ado-pr-guard.sh").read_text()
pattern = (here.parent / "patterns.ere").read_text().splitlines()[0]
body = "\n".join(guard.splitlines()[1:]) + "\n"  # drop the shebang
GUARD = "tools/attribution-guard/azure-devops/ado-pr-guard.sh"
PATTERNS = "tools/attribution-guard/patterns.ere"


def ind(s, n):
    return textwrap.indent(s, " " * n, lambda _l: True).replace(" " * n + "\n", "\n")


prep = f"""set -euo pipefail
# Patterns come from the TARGET branch (first parent of the PR merge commit), never from the PR.
out="$AGENT_TEMPDIRECTORY/attribution-patterns.ere"
if git cat-file -e 'HEAD^1:{PATTERNS}' 2>/dev/null; then
  git show 'HEAD^1:{PATTERNS}' > "$out"
  echo "Using {PATTERNS} from the target branch."
else
  cat > "$out" <<'ERE'
{pattern}
ERE
  echo "Target branch has no {PATTERNS}; using the embedded default."
fi
"""

bv = f"""# attribution-guard - REQUIRED build validation for pull requests (Azure Repos).
# Fails when the PR title, PR description, auto-complete merge commit message, any commit message
# or commit author in the PR, or any PR comment carries AI attribution or a chat/session link
# (patterns: {PATTERNS} on the TARGET branch; embedded default otherwise).
# The word "claude" alone (claude-security, claude-plugins-official) passes.
#
# Copy to the work repository as .azure-pipelines/attribution-guard.yml; setup-azure-devops.sh
# registers it as a required build validation policy. It does NOT re-run when only the description
# or a comment changes; attribution-guard-status.yml (service hooks + PR status policy) closes that.
# The build service identity needs 'Contribute to pull requests' on the repo for GUARD_SANITIZE.
# Generated by tools/attribution-guard/azure-devops/gen.py from ado-pr-guard.sh; do not edit here.
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard
  displayName: attribution-guard
  timeoutInMinutes: 10
  steps:
  - checkout: self
    fetchDepth: 0            # full history: PR commits are HEAD^1..HEAD^2 of the merge commit
    fetchTags: false
    persistCredentials: false

  - bash: |
{ind(prep, 6)}    displayName: Load patterns from the target branch

  - bash: |
{ind(body, 6)}    displayName: Check PR text, commits and comments
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)      # secrets are never mapped into env implicitly
      COLLECTION_URI: $(System.CollectionUri)
      PROJECT_ID: $(System.TeamProjectId)
      REPO_ID: $(Build.Repository.ID)
      PR_ID: $(System.PullRequest.PullRequestId)     # stays a literal macro outside PR builds -> fails closed
      PATTERN_FILE: $(Agent.TempDirectory)/attribution-patterns.ere
      GUARD_GIT_RANGE: HEAD^1..HEAD^2
      GUARD_SANITIZE: '1'
"""

audit_step = f"""set -euo pipefail
export LC_ALL=C
# The completer can still edit the merge commit message in the completion dialog after every PR
# check passed, and bypass rights allow direct pushes: check what actually landed. Detection only.
if git cat-file -e 'HEAD:{PATTERNS}' 2>/dev/null; then
  ATTRIB_RE=$(git show 'HEAD:{PATTERNS}' | sed -n 1p)
else
  ATTRIB_RE=$(cat <<'ERE'
{pattern}
ERE
)
fi
ATTRIB_ZW=$'\\xe2\\x80\\x8b|\\xe2\\x80\\x8c|\\xe2\\x80\\x8d|\\xe2\\x81\\xa0|\\xef\\xbb\\xbf'
export ATTRIB_RE ATTRIB_ZW
# A merge commit brings its second-parent history; a squash or direct push is the commit itself.
if [[ $(git rev-list --parents -n 1 HEAD | wc -w) -ge 3 ]]; then range=(HEAD^1..HEAD); else range=(-1 HEAD); fi
fail=0
while IFS= read -r c; do
  lines=$(git log -1 --format=%B "$c" | awk 'BEGIN {{ re = tolower(ENVIRON["ATTRIB_RE"]); zw = ENVIRON["ATTRIB_ZW"] }}
    {{ s = $0; gsub(zw, "", s); if (tolower(s) ~ re) printf "%d ", NR }}')
  if [[ -n $lines ]]; then
    echo "##vso[task.logissue type=error]AI attribution landed on $BUILD_SOURCEBRANCHNAME in commit ${{c:0:8}}, line(s) $lines"; fail=1
  fi
  for who in ae ce; do
    if git log -1 --format="%$who" "$c" | grep -Eiq '@anthropic\\.com$'; then
      echo "##vso[task.logissue type=error]commit ${{c:0:8}} has the vendor identity as $([[ $who == ae ]] && echo author || echo committer)"; fail=1
    fi
  done
done < <(git rev-list "${{range[@]}}")
[[ $fail -eq 0 ]] || {{ echo "Revert or rewrite the commit; see docs/ATTRIBUTION.md."; exit 1; }}
echo "No AI attribution in the commits that landed."
"""

audit = f"""# attribution-audit - runs on every push to the protected branch of a WORK repository and fails
# (red build + notification) when the commit that landed carries AI attribution or has the vendor
# identity as author or committer. Detection only: it catches a merge message edited in the
# completion dialog and pushes by people with bypass rights. Patterns: {PATTERNS} on that
# branch, embedded default otherwise.
# Copy to the work repository as .azure-pipelines/attribution-audit.yml; setup-azure-devops.sh
# creates the pipeline. Generated by tools/attribution-guard/azure-devops/gen.py; do not edit here.
trigger:
  branches:
    include: [main]
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_audit
  displayName: attribution-audit
  timeoutInMinutes: 10
  steps:
  - checkout: self
    fetchDepth: 100
    fetchTags: false
    persistCredentials: false
  - bash: |
{ind(audit_step, 6)}    displayName: Check the commits that landed
"""

dispatch_hook = f"""set -euo pipefail
# Event payload is an untrusted hint: only ids are read, validated here and by the guard, and allow-listed.
pr=${{HOOK_PR_ID:-$HOOK_PR_ID2}}
repo=${{HOOK_REPO_ID:-$HOOK_REPO_ID2}}
proj=${{HOOK_PROJECT_ID:-$HOOK_PROJECT_ID2}}
[[ $pr =~ ^[1-9][0-9]{{0,9}}$ ]] || {{ echo "##vso[task.logissue type=error]attribution-guard: event without a valid pull request id"; exit 2; }}
key=$(printf '%s/%s' "$proj" "$repo" | tr '[:upper:]' '[:lower:]')
case " $(printf '%s' "$GUARD_REPOS" | tr '[:upper:]' '[:lower:]') " in
  *" $key "*) ;;
  *) echo "Event for a repository that is not in GUARD_REPOS; nothing to do."; exit 0 ;;
esac
export GUARD_TARGET_URL="${{SYSTEM_COLLECTIONURI}}${{SYSTEM_TEAMPROJECTID}}/_build/results?buildId=${{BUILD_BUILDID}}"
PROJECT_ID=$proj REPO_ID=$repo PR_ID=$pr bash "$BUILD_SOURCESDIRECTORY/{GUARD}"
"""
dispatch_sweep = f"""set -euo pipefail
export GUARD_TARGET_URL="${{SYSTEM_COLLECTIONURI}}${{SYSTEM_TEAMPROJECTID}}/_build/results?buildId=${{BUILD_BUILDID}}"
rc=0
for pair in $GUARD_REPOS; do
  proj=${{pair%%/*}}; repo=${{pair#*/}}
  url="${{SYSTEM_COLLECTIONURI}}${{proj}}/_apis/git/repositories/${{repo}}/pullrequests?searchCriteria.status=active&\\$top=1000&api-version=7.1"
  ids=$(curl -sS --fail-with-body --retry 3 -H "Authorization: Bearer ${{SYSTEM_ACCESSTOKEN}}" "$url" | jq -r '.value[].pullRequestId')
  for id in $ids; do
    echo "== $pair PR $id"
    PROJECT_ID=$proj REPO_ID=$repo PR_ID=$id bash "$BUILD_SOURCESDIRECTORY/{GUARD}" || rc=1
  done
done
exit "$rc"
"""
common_env = f"""      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      COLLECTION_URI: $(System.CollectionUri)
      PATTERN_FILE: $(Build.SourcesDirectory)/{PATTERNS}
      GUARD_STATUS: '1'
      GUARD_SANITIZE: '1'
"""
hdr = """# Runs from the PROTECTED guard repository: an import of lucas4790/my-claude-skills in a separate
# project with 'Limit job authorization scope to current project' on. PR authors cannot change this
# YAML, the guard or the patterns, and the status policy only counts statuses from this pipeline's
# build service identity ("Authorized identity"). Generated by gen.py; do not edit here.
"""
repos_block = """  repositories:            # every guarded repository; also required by 'Protect access to repositories'
  - repository: guarded1
    type: git
    name: WorkProject/WorkRepo
variables:
  # "<projectId>/<repositoryId>" pairs (GUIDs), space separated; must match the repositories above.
  GUARD_REPOS: '00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000'
"""
status = f"""# attribution-guard-status - posts PR status attribution-guard/no-ai-attribution on every
# "Pull request created/updated/commented on" service-hook event, so description edits and new
# comments are re-checked (build validation only re-runs on pushes).
{hdr}trigger: none
pr: none

resources:
  webhooks:
  - webhook: WebHook                      # alias read by the parameters.WebHook.* expressions below
    connection: attribution-guard-hook    # Incoming WebHook service connection (WebHook Name: attribution-guard)
{repos_block}
pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard_status
  displayName: attribution-guard status
  timeoutInMinutes: 10
  uses:
    repositories: [guarded1]
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: false
  - bash: |
{ind(dispatch_hook, 6)}    displayName: Check the PR named by the event
    env:
{common_env}      HOOK_PR_ID: ${{{{ parameters.WebHook.resource.pullRequestId }}}}                          # PR created/updated
      HOOK_PR_ID2: ${{{{ parameters.WebHook.resource.pullRequest.pullRequestId }}}}             # PR commented on
      HOOK_REPO_ID: ${{{{ parameters.WebHook.resource.repository.id }}}}
      HOOK_REPO_ID2: ${{{{ parameters.WebHook.resource.pullRequest.repository.id }}}}
      HOOK_PROJECT_ID: ${{{{ parameters.WebHook.resource.repository.project.id }}}}
      HOOK_PROJECT_ID2: ${{{{ parameters.WebHook.resource.pullRequest.repository.project.id }}}}
"""
sweep = f"""# attribution-guard-sweep - re-checks every ACTIVE pull request in GUARD_REPOS on a schedule and
# re-posts attribution-guard/no-ai-attribution. Safety net for missed or undelivered service-hook events.
{hdr}trigger: none
pr: none

schedules:
- cron: '7,37 * * * *'        # UTC, twice an hour
  displayName: sweep active PRs
  branches:
    include: [main]
  always: true                # run even when this repository did not change

resources:
{repos_block}
pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard_sweep
  displayName: attribution-guard sweep
  timeoutInMinutes: 30
  uses:
    repositories: [guarded1]
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: false
  - bash: |
{ind(dispatch_sweep, 6)}    displayName: Check all active PRs
    env:
{common_env}"""

files = {
    "attribution-guard.yml": bv,
    "attribution-audit.yml": audit,
    "attribution-guard-status.yml": status,
    "attribution-guard-sweep.yml": sweep,
}
# The bash steps of each pipeline, in order: tests run exactly these scripts.
steps = {
    "attribution-guard.yml": [prep, body],
    "attribution-audit.yml": [audit_step],
    "attribution-guard-status.yml": [dispatch_hook],
    "attribution-guard-sweep.yml": [dispatch_sweep],
}


def main(argv):
    # Azure Pipelines expands $(name) macros inside inline scripts before bash runs; a command
    # substitution without arguments, like $(date), would be replaced or break. Refuse to generate one.
    for n, scripts in steps.items():
        for script in scripts:
            macros = re.findall(r"\$\([A-Za-z_][A-Za-z0-9_.]*\)", script)
            if macros:
                print(f"{n}: Azure Pipelines would expand {sorted(set(macros))}; add an argument or rename")
                return 1
    out = here / "pipelines"
    if "--extract" in argv:  # gen.py --extract DIR: write <pipeline>.step<N>.sh for the tests
        d = pathlib.Path(argv[argv.index("--extract") + 1])
        d.mkdir(parents=True, exist_ok=True)
        for n, scripts in steps.items():
            for i, script in enumerate(scripts, 1):
                (d / f"{n}.step{i}.sh").write_text(script)
        return 0
    if "--check" in argv:
        stale = [n for n, text in files.items() if not (out / n).exists() or (out / n).read_text() != text]
        if stale:
            print("stale (run python3 tools/attribution-guard/azure-devops/gen.py): " + ", ".join(stale))
            return 1
        print("pipelines up to date")
        return 0
    out.mkdir(exist_ok=True)
    for n, text in files.items():
        (out / n).write_text(text)
    print("generated " + ", ".join(files))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
