#!/usr/bin/env python3
"""Generate the Azure Pipelines YAML files from ado-pr-guard.sh, ../patterns.ere and ../match.awk
(single source).

  python3 gen.py                 write pipelines/*.yml
  python3 gen.py --check         exit 1 when pipelines/*.yml differ from what would be generated
  python3 gen.py --extract DIR   write each pipeline's bash steps to DIR (used by tests/)

pipelines/attribution-guard.yml (build validation) and pipelines/attribution-audit.yml (push audit)
go into each WORK repository (e.g. .azure-pipelines/); the first embeds the guard. The status and sweep pipelines run from a PROTECTED guard repository that is an import of
this repository, so they reference tools/attribution-guard/... paths directly.
"""
import pathlib
import re
import sys
import textwrap

here = pathlib.Path(__file__).resolve().parent
guard = (here / "ado-pr-guard.sh").read_text()
pattern = (here.parent / "patterns.ere").read_text().splitlines()[0]
matcher = (here.parent / "match.awk").read_text()
GUARD = "tools/attribution-guard/azure-devops/ado-pr-guard.sh"
PATTERNS = "tools/attribution-guard/patterns.ere"
# The matcher shared with the GitHub workflows, inline: the build validation and audit pipelines
# run in the WORK repository, which has no tools/attribution-guard/match.awk.
if not matcher.endswith("\n") or "\nAWK\n" in "\n" + matcher:
    sys.exit("gen.py: match.awk must end with a newline and have no line 'AWK'")
EMBED = "IFS= read -r -d '' ATTRIB_AWK <<'AWK' || true  # tools/attribution-guard/match.awk\n" + matcher + "AWK\n"
# ado-pr-guard.sh reads match.awk from its parent directory; the generated copy carries it inline.
LOAD = 'ATTRIB_AWK=$(cat "$(dirname "${BASH_SOURCE[0]}")/../match.awk") || die "tools/attribution-guard/match.awk is missing."\n'
if guard.count(LOAD) != 1:
    sys.exit("gen.py: ado-pr-guard.sh no longer loads match.awk with the line gen.py replaces (LOAD)")
body = "\n".join(guard.splitlines()[1:]).replace(LOAD.rstrip("\n"), EMBED.rstrip("\n")) + "\n"  # drop the shebang


def ind(s, n):
    return textwrap.indent(s, " " * n, lambda _l: True).replace(" " * n + "\n", "\n")


prep = f"""set -euo pipefail
# Patterns come from the TARGET branch (first parent of the PR merge commit), never from the PR.
out="$AGENT_TEMPDIRECTORY/attribution-patterns.ere"
if git cat-file -e 'HEAD^1:{PATTERNS}' 2>/dev/null; then
  git show 'HEAD^1:{PATTERNS}' > "$out"
  echo "Using {PATTERNS} from the target branch."
else
  cat > "$out" <<'ERE'
{pattern}
ERE
  echo "Target branch has no {PATTERNS}; using the embedded default."
fi
"""

bv = f"""# attribution-guard - REQUIRED build validation for pull requests (Azure Repos).
# Fails when the PR title, PR description, auto-complete merge commit message, any commit message
# or commit author in the PR, or any PR comment carries AI attribution or a chat/session link
# (patterns: {PATTERNS} on the TARGET branch; embedded default otherwise).
# The word "claude" alone (claude-security, claude-plugins-official) passes.
#
# Copy to the work repository as .azure-pipelines/attribution-guard.yml; setup-azure-devops.sh
# registers it as a required build validation policy. It does NOT re-run when only the description
# or a comment changes; attribution-guard-status.yml (service hooks + PR status policy) closes that.
# The build service identity needs 'Contribute to pull requests' on the repo for GUARD_SANITIZE.
# Generated by tools/attribution-guard/azure-devops/gen.py from ado-pr-guard.sh; do not edit here.
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard
  displayName: attribution-guard
  timeoutInMinutes: 10
  steps:
  - checkout: self
    fetchDepth: 0            # full history: PR commits are HEAD^1..HEAD^2 of the merge commit
    fetchTags: false
    persistCredentials: false

  - bash: |
{ind(prep, 6)}    displayName: Load patterns from the target branch

  - bash: |
{ind(body, 6)}    displayName: Check PR text, commits and comments
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)      # secrets are never mapped into env implicitly
      COLLECTION_URI: $(System.CollectionUri)
      PROJECT_ID: $(System.TeamProjectId)
      REPO_ID: $(Build.Repository.ID)
      PR_ID: $(System.PullRequest.PullRequestId)     # stays a literal macro outside PR builds -> fails closed
      PATTERN_FILE: $(Agent.TempDirectory)/attribution-patterns.ere
      GUARD_GIT_RANGE: HEAD^1..HEAD^2
      GUARD_SANITIZE: '1'
"""

audit_step = f"""set -euo pipefail
export LC_ALL=C
# The completer can still edit the merge commit message in the completion dialog after every PR
# check passed, and bypass rights allow direct pushes: check what actually landed. Detection only.
err() {{ echo "##vso[task.logissue type=error]attribution-audit: $1"; exit 2; }}

# The commit the previous run of this pipeline checked on this branch: only runs that finished the
# check count (they carry the attribution-audited tag), so a cancelled or broken run moves nothing.
url="${{SYSTEM_COLLECTIONURI%/}}/${{SYSTEM_TEAMPROJECTID}}/_apis/build/builds?definitions=${{SYSTEM_DEFINITIONID}}&branchName=${{BUILD_SOURCEBRANCH}}&statusFilter=completed&tagFilters=attribution-audited&queryOrder=finishTimeDescending&\\$top=1&api-version=7.1"
prev=$(curl -sS --fail-with-body --retry 3 -H "Authorization: Bearer ${{SYSTEM_ACCESSTOKEN}}" "$url" \\
  | jq -r '.value[0].sourceVersion // empty') || err "could not read the previous run of this pipeline."
[[ -z $prev || $prev =~ ^[0-9a-f]{{40}}$ ]] || err "unexpected previous commit id."

if [[ -z $prev ]]; then
  echo "First run on this branch: checking the latest commit (and a merge's second-parent history)."
  if [[ $(git rev-list --parents -n 1 HEAD | wc -w) -ge 3 ]]; then range=(HEAD^1..HEAD); else range=(-1 HEAD); fi
elif git cat-file -e "$prev^{{commit}}" 2>/dev/null && git merge-base --is-ancestor "$prev" HEAD; then
  range=("$prev..HEAD")
elif git cat-file -e "$prev^{{commit}}" 2>/dev/null && git merge-base --is-ancestor HEAD "$prev"; then
  echo "A later run already checked $prev, which contains this commit; nothing to do."
  echo "##vso[build.addbuildtag]attribution-audited"; exit 0
else
  err "commit ${{prev:0:8}} from the previous run is not in the fetched history of HEAD (force-push, or more than fetchDepth commits); check the branch by hand."
fi
# Patterns from the commit the previous run checked, never from the push being audited (it could
# weaken them); the embedded default before the first run.
if [[ -n $prev ]] && git cat-file -e "$prev:{PATTERNS}" 2>/dev/null; then
  ATTRIB_RE=$(git show "$prev:{PATTERNS}" | sed -n 1p)
else
  ATTRIB_RE=$(cat <<'ERE'
{pattern}
ERE
)
fi
export ATTRIB_RE
# The matcher; its self-test fails on a pattern that does not compile (some awks treat one as never
# matching), misses a known trailer (ATTRIB_CANARY replaces it) or matches a plain word.
{EMBED}awk -v mode=selftest "$ATTRIB_AWK" </dev/null 2>/dev/null \\
  || err "the attribution pattern does not compile or fails its self-test."

# A range that reaches the shallow boundary would silently skip older side-branch commits.
shallow=$(git rev-parse --git-path shallow)
if [[ -s $shallow ]] && git rev-list "${{range[@]}}" | grep -qFxf "$shallow"; then
  err "the commits to check reach past the fetched history (fetchDepth); fetch more and run again."
fi
fail=0 n=0
while IFS= read -r c; do
  n=$((n + 1))
  lines=$(git log -1 --format=%B "$c" | awk -v mode=report "$ATTRIB_AWK" | tr '\\n' ' ')
  if [[ -n $lines ]]; then
    echo "##vso[task.logissue type=error]AI attribution landed on $BUILD_SOURCEBRANCHNAME in commit ${{c:0:8}}, line(s) $lines"; fail=1
  fi
  for who in ae ce; do
    if git log -1 --format="%$who" "$c" | grep -Eiq '@anthropic\\.com$'; then
      echo "##vso[task.logissue type=error]commit ${{c:0:8}} has the vendor identity as $([[ $who == ae ]] && echo author || echo committer)"; fail=1
    fi
  done
done < <(git rev-list "${{range[@]}}")
echo "Checked $n commit(s)."
echo "##vso[build.addbuildtag]attribution-audited"   # the next run starts after this commit
[[ $fail -eq 0 ]] || {{ echo "Revert or rewrite the commit; see docs/ATTRIBUTION.md."; exit 1; }}
echo "No AI attribution in the commits that landed."
"""

audit = f"""# attribution-audit - runs on every push to the protected branch of a WORK repository and fails
# (red build + notification) when the commit that landed carries AI attribution or has the vendor
# identity as author or committer. It checks every commit since the one its previous completed
# check covered, with the patterns of that commit (embedded default on the first run). Detection
# only: it catches a merge message edited in the completion dialog and pushes by people with bypass
# rights. Limit: a push to the branch also brings its own version of this YAML (Azure runs CI with
# the pushed YAML), so someone with bypass rights can change the audit in the same push; review
# changes to .azure-pipelines/ and consider running it from the protected guard project instead.
# Copy to the work repository as .azure-pipelines/attribution-audit.yml; setup-azure-devops.sh
# creates the pipeline. Generated by tools/attribution-guard/azure-devops/gen.py; do not edit here.
trigger:
  batch: true              # runs on the branch never overlap; each covers everything since the last
  branches:
    include: [main]        # the protected branch; setup-azure-devops.sh warns when BRANCH differs
pr: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_audit
  displayName: attribution-audit
  timeoutInMinutes: 10
  steps:
  - checkout: self
    fetchDepth: 500          # enough history to reach the commit the previous run checked
    fetchTags: false
    persistCredentials: false
  - bash: |
{ind(audit_step, 6)}    displayName: Check the commits that landed
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)      # reads the previous run of this pipeline
"""

dispatch_hook = f"""set -euo pipefail
# Event payload is an untrusted hint: only ids are read, validated here and by the guard, and allow-listed.
pr=${{HOOK_PR_ID:-$HOOK_PR_ID2}}
repo=${{HOOK_REPO_ID:-$HOOK_REPO_ID2}}
proj=${{HOOK_PROJECT_ID:-$HOOK_PROJECT_ID2}}
[[ $pr =~ ^[1-9][0-9]{{0,9}}$ ]] || {{ echo "##vso[task.logissue type=error]attribution-guard: event without a valid pull request id"; exit 2; }}
key=$(printf '%s/%s' "$proj" "$repo" | tr '[:upper:]' '[:lower:]')
case " $(printf '%s' "$GUARD_REPOS" | tr '[:upper:]' '[:lower:]') " in
  *" $key "*) ;;
  *) echo "Event for a repository that is not in GUARD_REPOS; nothing to do."; exit 0 ;;
esac
export GUARD_TARGET_URL="${{SYSTEM_COLLECTIONURI}}${{SYSTEM_TEAMPROJECTID}}/_build/results?buildId=${{BUILD_BUILDID}}"
PROJECT_ID=$proj REPO_ID=$repo PR_ID=$pr bash "$BUILD_SOURCESDIRECTORY/{GUARD}"
"""
dispatch_sweep = f"""set -euo pipefail
export GUARD_TARGET_URL="${{SYSTEM_COLLECTIONURI}}${{SYSTEM_TEAMPROJECTID}}/_build/results?buildId=${{BUILD_BUILDID}}"
rc=0
for pair in $GUARD_REPOS; do
  proj=${{pair%%/*}}; repo=${{pair#*/}}
  url="${{SYSTEM_COLLECTIONURI}}${{proj}}/_apis/git/repositories/${{repo}}/pullrequests?searchCriteria.status=active&\\$top=1000&api-version=7.1"
  ids=$(curl -sS --fail-with-body --retry 3 -H "Authorization: Bearer ${{SYSTEM_ACCESSTOKEN}}" "$url" | jq -r '.value[].pullRequestId')
  for id in $ids; do
    echo "== $pair PR $id"
    PROJECT_ID=$proj REPO_ID=$repo PR_ID=$id bash "$BUILD_SOURCESDIRECTORY/{GUARD}" || rc=1
  done
done
exit "$rc"
"""
common_env = f"""      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      COLLECTION_URI: $(System.CollectionUri)
      PATTERN_FILE: $(Build.SourcesDirectory)/{PATTERNS}
      GUARD_STATUS: '1'
      GUARD_SANITIZE: '1'
"""
hdr = """# Runs from the PROTECTED guard repository: an import of lucas4790/my-claude-skills in a separate
# project with 'Limit job authorization scope to current project' on. PR authors cannot change this
# YAML, the guard or the patterns, and the status policy only counts statuses from this pipeline's
# build service identity ("Authorized identity"). Generated by gen.py; do not edit here.
"""
repos_block = """  repositories:            # every guarded repository; also required by 'Protect access to repositories'
  - repository: guarded1
    type: git
    name: WorkProject/WorkRepo
variables:
  # "<projectId>/<repositoryId>" pairs (GUIDs), space separated; must match the repositories above.
  GUARD_REPOS: '00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000'
"""
status = f"""# attribution-guard-status - posts PR status attribution-guard/no-ai-attribution on every
# "Pull request created/updated/commented on" service-hook event, so description edits and new
# comments are re-checked (build validation only re-runs on pushes).
{hdr}trigger: none
pr: none

resources:
  webhooks:
  - webhook: WebHook                      # alias read by the parameters.WebHook.* expressions below
    connection: attribution-guard-hook    # Incoming WebHook service connection (WebHook Name: attribution-guard)
{repos_block}
pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard_status
  displayName: attribution-guard status
  timeoutInMinutes: 10
  uses:
    repositories: [guarded1]
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: false
  - bash: |
{ind(dispatch_hook, 6)}    displayName: Check the PR named by the event
    env:
{common_env}      HOOK_PR_ID: ${{{{ parameters.WebHook.resource.pullRequestId }}}}                          # PR created/updated
      HOOK_PR_ID2: ${{{{ parameters.WebHook.resource.pullRequest.pullRequestId }}}}             # PR commented on
      HOOK_REPO_ID: ${{{{ parameters.WebHook.resource.repository.id }}}}
      HOOK_REPO_ID2: ${{{{ parameters.WebHook.resource.pullRequest.repository.id }}}}
      HOOK_PROJECT_ID: ${{{{ parameters.WebHook.resource.repository.project.id }}}}
      HOOK_PROJECT_ID2: ${{{{ parameters.WebHook.resource.pullRequest.repository.project.id }}}}
"""
sweep = f"""# attribution-guard-sweep - re-checks every ACTIVE pull request in GUARD_REPOS on a schedule and
# re-posts attribution-guard/no-ai-attribution. Safety net for missed or undelivered service-hook events.
{hdr}trigger: none
pr: none

schedules:
- cron: '7,37 * * * *'        # UTC, twice an hour
  displayName: sweep active PRs
  branches:
    include: [main]
  always: true                # run even when this repository did not change

resources:
{repos_block}
pool:
  vmImage: ubuntu-latest

jobs:
- job: attribution_guard_sweep
  displayName: attribution-guard sweep
  timeoutInMinutes: 30
  uses:
    repositories: [guarded1]
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: false
  - bash: |
{ind(dispatch_sweep, 6)}    displayName: Check all active PRs
    env:
{common_env}"""

files = {
    "attribution-guard.yml": bv,
    "attribution-audit.yml": audit,
    "attribution-guard-status.yml": status,
    "attribution-guard-sweep.yml": sweep,
}
# The bash steps of each pipeline, in order: tests run exactly these scripts.
steps = {
    "attribution-guard.yml": [prep, body],
    "attribution-audit.yml": [audit_step],
    "attribution-guard-status.yml": [dispatch_hook],
    "attribution-guard-sweep.yml": [dispatch_sweep],
}


def main(argv):
    # Azure Pipelines expands $(name) macros inside inline scripts before bash runs; a command
    # substitution without arguments, like $(date), would be replaced or break. Refuse to generate one.
    for n, scripts in steps.items():
        for script in scripts:
            macros = re.findall(r"\$\([A-Za-z_][A-Za-z0-9_.]*\)", script)
            if macros:
                print(f"{n}: Azure Pipelines would expand {sorted(set(macros))}; add an argument or rename")
                return 1
    out = here / "pipelines"
    if "--extract" in argv:  # gen.py --extract DIR: write <pipeline>.step<N>.sh for the tests
        d = pathlib.Path(argv[argv.index("--extract") + 1])
        d.mkdir(parents=True, exist_ok=True)
        for n, scripts in steps.items():
            for i, script in enumerate(scripts, 1):
                (d / f"{n}.step{i}.sh").write_text(script)
        return 0
    if "--check" in argv:
        stale = [n for n, text in files.items() if not (out / n).exists() or (out / n).read_text() != text]
        if stale:
            print("stale (run python3 tools/attribution-guard/azure-devops/gen.py): " + ", ".join(stale))
            return 1
        print("pipelines up to date")
        return 0
    out.mkdir(exist_ok=True)
    for n, text in files.items():
        (out / n).write_text(text)
    print("generated " + ", ".join(files))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
