"""scripts/gen-catalog.py: SKILLS.md for a small fixture marketplace, compared byte for byte."""
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.dont_write_bytecode = True  # one test imports scripts/skill_descriptions.py: keep scripts/__pycache__ out of the checkout

LONG =("Builds very long descriptions for testing the cut. " * 6).strip()


def build(r) -> None:
    r.write_json(".claude-plugin/marketplace.json", {"name": "fixture", "plugins": [
        {"name": "alpha", "source": "./plugins/alpha", "description": "Alpha: skills, commands and agents."},
        {"name": "beta", "source": "./plugins/beta", "description": "Beta: declared skills only."},
        {"name": "gamma", "source": "./plugins/gamma", "description": "Gamma: a declared path is missing."},
        {"name": "ext", "source": {"source": "url", "url": "https://example.invalid/ext.git", "sha": "0" * 40},
         "description": "External (url)."},
        {"name": "gh", "source": {"source": "github", "repo": "owner/gh-plugin", "sha": "1" * 40},
         "description": "External (github)."},
        {"name": "empty", "source": "./plugins/empty", "description": "Nothing to list."},
    ]})
    # skills: folded, quoted, long, literal block, no frontmatter; listed in path order
    r.write("plugins/alpha/skills/b-folded/SKILL.md",
            "---\nname: b-folded\ndescription: >\n  Folded description\n  over two lines.\nlicense: MIT\n---\nBody.\n")
    r.write("plugins/alpha/skills/a-quoted/SKILL.md",
            "---\nname: 'a-quoted'\ndescription: \"Quoted: keeps the colon.\"\n---\nBody.\n")
    r.write("plugins/alpha/skills/c-long/SKILL.md", f"---\nname: c-long\ndescription: {LONG}\n---\n")
    r.write("plugins/alpha/skills/d-literal/SKILL.md",
            "---\nname: d-literal\ndescription: |-\n  Literal block,\n  joined too.\n---\n")
    r.write("plugins/alpha/skills/e-no-frontmatter/SKILL.md", "# Just a heading\n")
    r.write("plugins/alpha/commands/run.md", "---\ndescription: Runs alpha.\n---\nRun.\n")
    r.write("plugins/alpha/commands/sub/deep.md", "---\ndescription: A nested command.\n---\n")
    r.write("plugins/alpha/agents/reviewer.md",
            "---\nname: code-reviewer\ndescription: Reviews code. Use after a change.\ntools: Read\n---\n")
    # beta: plugin.json lists one skill; the other is left out of the catalog
    r.write_json("plugins/beta/.claude-plugin/plugin.json", {"name": "beta", "skills": ["./skills/listed"]})
    r.write("plugins/beta/skills/listed/SKILL.md", "---\nname: listed\ndescription: Listed.\n---\n")
    r.write("plugins/beta/skills/unlisted/SKILL.md", "---\nname: unlisted\ndescription: Not listed.\n---\n")
    # gamma: a declared skill folder is missing, so every SKILL.md is listed
    r.write_json("plugins/gamma/.claude-plugin/plugin.json", {"name": "gamma", "skills": ["./skills/one", "./skills/gone"]})
    r.write("plugins/gamma/skills/one/SKILL.md", "---\nname: one\ndescription: One.\n---\n")
    r.write("plugins/gamma/skills/two/SKILL.md", "---\nname: two\ndescription: Two.\n---\n")
    (r.root / "plugins/empty").mkdir(parents=True)


EXPECTED = """# Skills catalog

Generated by `scripts/gen-catalog.py` on every sync — do not edit by hand.

COSTS## `alpha`

Alpha: skills, commands and agents.

### Skills

| Name | What it does |
|---|---|
| [`a-quoted`](plugins/alpha/skills/a-quoted/SKILL.md) | Quoted: keeps the colon. |
| [`b-folded`](plugins/alpha/skills/b-folded/SKILL.md) | Folded description over two lines. |
| [`c-long`](plugins/alpha/skills/c-long/SKILL.md) | CUT |
| [`d-literal`](plugins/alpha/skills/d-literal/SKILL.md) | Literal block, joined too. |
| [`e-no-frontmatter`](plugins/alpha/skills/e-no-frontmatter/SKILL.md) |  |

### Commands

| Name | What it does |
|---|---|
| [`run`](plugins/alpha/commands/run.md) | Runs alpha. |
| [`deep`](plugins/alpha/commands/sub/deep.md) | A nested command. |

### Agents

| Name | What it does |
|---|---|
| [`code-reviewer`](plugins/alpha/agents/reviewer.md) | Reviews code. Use after a change. |

## `beta`

Beta: declared skills only.

### Skills

| Name | What it does |
|---|---|
| [`listed`](plugins/beta/skills/listed/SKILL.md) | Listed. |

## `gamma`

Gamma: a declared path is missing.

### Skills

| Name | What it does |
|---|---|
| [`one`](plugins/gamma/skills/one/SKILL.md) | One. |
| [`two`](plugins/gamma/skills/two/SKILL.md) | Two. |

## `ext`

External (url).

Referenced from upstream: https://example.invalid/ext.git

## `gh`

External (github).

Referenced from upstream: owner/gh-plugin

## `empty`

Nothing to list.
"""


INTRO = ("Claude Code puts one line per skill and command (`- plugin:name: description`) into the model's context in "
         "every session. These tables count those characters, including the line break after each entry "
         "(`README.md`, \"Listing budget\"). Copilot CLI is assumed to list the same way: its format and what it does "
         "over its budget are not verified, so its column uses the same count. Skills with "
         "`disable-model-invocation: true` are not listed and agents are not part of it. \"Names only\" is what "
         "stays when a client drops every description.")


def cost(plugin: str, name: str, text: str) -> int:
    """One listing entry: "- plugin:name: text" and a line break."""
    return len(f"{plugin}:{name}") + 5 + len(text)


def floor(plugin: str, name: str) -> int:
    """The same entry without its description: "- plugin:name" and a line break."""
    return len(f"{plugin}:{name}") + 3


def expected_costs() -> str:
    alpha = [("a-quoted", "Quoted: keeps the colon."), ("b-folded", "Folded description over two lines."),
             ("c-long", LONG), ("d-literal", "Literal block, joined too."), ("e-no-frontmatter", ""),
             ("run", "Runs alpha."), ("deep", "A nested command.")]
    a_chars = sum(cost("alpha", n, t) for n, t in alpha)
    a_names = sum(floor("alpha", n) for n, _ in alpha)
    b_chars, b_names = cost("beta", "listed", "Listed."), floor("beta", "listed")
    g_chars = cost("gamma", "one", "One.") + cost("gamma", "two", "Two.")
    g_names = floor("gamma", "one") + floor("gamma", "two")
    rows = sorted([("alpha", 5, 2, a_chars, a_names), ("beta", 1, 0, b_chars, b_names), ("gamma", 2, 0, g_chars, g_names),
                   ("empty", 0, 0, 0, 0)], key=lambda r: (-r[3], r[0]))
    table = "".join(f"| `{n}` | – | {sk} | {cm} | {c:,} | {f:,} |\n" for n, sk, cm, c, f in rows)
    return (f"## Listing cost\n\n{INTRO}\n\n### Per plugin\n\n"
            "| Plugin | Profile | Skills | Commands | Characters | Names only |\n|---|---|---|---|---|---|\n"
            f"{table}| `ext` | – | – | – | not measured | – |\n| `gh` | – | – | – | not measured | – |\n\n")


def expected_cut() -> str:
    """first_sentence(): whitespace collapsed, cut at the last space within 220 characters, plus an ellipsis."""
    cut = LONG[:220]
    return cut[: cut.rfind(" ")] + "…"


def test_catalog_matches_the_expected_markdown(bare_layout):
    build(bare_layout)
    res = bare_layout.gen_catalog()
    assert res.stdout == "==> wrote SKILLS.md (6 plugins)\n"
    assert bare_layout.read("SKILLS.md") == EXPECTED.replace("CUT", expected_cut()).replace("COSTS", expected_costs())


def test_long_description_is_cut_at_a_word_boundary(bare_layout):
    build(bare_layout)
    bare_layout.gen_catalog()
    row = next(x for x in bare_layout.read("SKILLS.md").splitlines() if "c-long" in x)
    text = row.split(" | ", 1)[1].removesuffix(" |")
    assert len(LONG) > 220
    assert text.endswith("…") and len(text) <= 221
    assert LONG.startswith(text[:-1]) and LONG[len(text) - 1] == " "


def test_output_is_deterministic(bare_layout):
    build(bare_layout)
    bare_layout.gen_catalog()
    first = bare_layout.path("SKILLS.md").read_bytes()
    bare_layout.gen_catalog()
    assert bare_layout.path("SKILLS.md").read_bytes() == first
    assert first.endswith(b"\n") and not first.endswith(b"\n\n")


def test_marketplace_order_is_kept(bare_layout):
    build(bare_layout)
    bare_layout.edit_json(".claude-plugin/marketplace.json", lambda d: d["plugins"].reverse())
    bare_layout.gen_catalog()
    headings = [x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("## `")]
    assert headings == ["## `empty`", "## `gh`", "## `ext`", "## `gamma`", "## `beta`", "## `alpha`"]


def test_pipe_in_a_description_does_not_break_the_table(bare_layout):
    bare_layout.write_json(".claude-plugin/marketplace.json",
                           {"plugins": [{"name": "p", "source": "./plugins/p", "description": "P"}]})
    bare_layout.write("plugins/p/skills/s/SKILL.md", "---\nname: s\ndescription: Reads a | b tables.\n---\n")
    bare_layout.gen_catalog()
    row = next(x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("| [`s`]"))
    assert row == "| [`s`](plugins/p/skills/s/SKILL.md) | Reads a \\| b tables. |"


def test_values_are_read_like_validate_py_and_the_evals_read_them(bare_layout):
    """One frontmatter parser (scripts/skill_descriptions.py): an unmatched quote stays, `>+` / `|+` block
    scalars are blocks, keys may hold digits."""
    bare_layout.write_json(".claude-plugin/marketplace.json",
                           {"plugins": [{"name": "p", "source": "./plugins/p", "description": "P"}]})
    bare_layout.write("plugins/p/skills/a/SKILL.md", '---\nname: a\ndescription: Use when you run "make"\n---\n')
    bare_layout.write("plugins/p/skills/b/SKILL.md", "---\nname: b\ndescription: >+\n  Folded, keep.\n---\n")
    bare_layout.write("plugins/p/agents/x.md", "---\nx-y1: 1\nname: agent-x\ndescription: |+\n  Literal.\n---\n")
    bare_layout.gen_catalog()
    rows = [x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("| [`")]
    assert rows == ['| [`a`](plugins/p/skills/a/SKILL.md) | Use when you run "make" |',
                    "| [`b`](plugins/p/skills/b/SKILL.md) | Folded, keep. |",
                    "| [`agent-x`](plugins/p/agents/x.md) | Literal. |"]


def test_a_blank_line_in_a_block_description_does_not_cut_it(bare_layout):
    bare_layout.write_json(".claude-plugin/marketplace.json",
                           {"plugins": [{"name": "p", "source": "./plugins/p", "description": "P"}]})
    bare_layout.write("plugins/p/skills/a/SKILL.md", "---\nname: a\ndescription: >-\n\n  Starts after a blank.\n---\n")
    bare_layout.write("plugins/p/agents/x.md",
                      "---\nname: agent-x\ndescription: |\n  First paragraph.\n\n  Use when: second.\ntools: Read\n---\n")
    bare_layout.gen_catalog()
    rows = [x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("| [`")]
    assert rows == ["| [`a`](plugins/p/skills/a/SKILL.md) | Starts after a blank. |",
                    "| [`agent-x`](plugins/p/agents/x.md) | First paragraph. Use when: second. |"]


def test_the_repo_catalog_is_generated_from_the_committed_marketplace(tmp_path):
    """Smoke test on the real layout, copied: gen-catalog.py runs and covers every marketplace plugin."""
    root = tmp_path / "copy"
    shutil.copytree(REPO / "plugins", root / "plugins")
    shutil.copytree(REPO / ".claude-plugin", root / ".claude-plugin")
    (root / "scripts").mkdir()
    for script in ("gen-catalog.py", "skill_descriptions.py"):   # gen-catalog imports the shared parser
        shutil.copy2(REPO / "scripts" / script, root / "scripts" / script)
    res = subprocess.run([sys.executable, str(root / "scripts/gen-catalog.py")], capture_output=True, text=True)
    assert res.returncode == 0, res.stderr
    names = [p["name"] for p in json.loads((root / ".claude-plugin/marketplace.json").read_text())["plugins"]]
    text = (root / "SKILLS.md").read_text(encoding="utf-8")
    for n in names:
        assert f"## `{n}`" in text


# --- the "Listing cost" section ------------------------------------------------------------------------------

def cost_rows(text: str, heading: str) -> list[str]:
    """The table under `### heading` of the Listing cost section: header, separator and rows."""
    lines = text.splitlines()
    start = lines.index(f"### {heading}") + 2          # past the blank line
    rows = []
    for line in lines[start:]:
        if not line.startswith("|"):
            break
        rows.append(line)
    return rows


def cost_fixture(r) -> None:
    r.write_json(".claude-plugin/marketplace.json", {"plugins": [
        {"name": "a", "source": "./plugins/a", "description": "A"},
        {"name": "b", "source": "./plugins/b", "description": "B"},
        {"name": "c", "source": "./plugins/c", "description": "C (in no profile)"},
        {"name": "up", "source": {"source": "url", "url": "https://example.invalid/up.git", "sha": "0" * 40},
         "description": "External"}]})
    r.write("plugins/a/skills/s1/SKILL.md", "---\nname: s1\ndescription: Does one thing.\n---\n")
    r.write("plugins/a/skills/s2/SKILL.md", "---\nname: s2\ndescription: Does another thing.\n---\n")
    r.write("plugins/a/skills/hidden/SKILL.md",
            "---\nname: hidden\ndescription: Never listed.\ndisable-model-invocation: true\n---\n")
    r.write("plugins/b/commands/go.md", "---\ndescription: Goes.\n---\n")
    r.write("plugins/c/skills/s3/SKILL.md", "---\nname: s3\ndescription: Third.\n---\n")
    r.write_json("profiles.json", {"profiles": {"one": ["a", "up"], "two": ["b", "ghost"]}, "copilotDefault": ["one"],
                                   "listingBudget": {"$comment": "x",
                                                     "first": {"label": "First CLI", "chars": 100, "profiles": ["one"]},
                                                     "second": {"chars": 30, "profiles": ["one", "two"]}}})


def test_cost_tables_show_profiles_budgets_and_what_is_not_measured(bare_layout):
    cost_fixture(bare_layout)
    bare_layout.gen_catalog()
    text = bare_layout.read("SKILLS.md")
    a = cost("a", "s1", "Does one thing.") + cost("a", "s2", "Does another thing.")
    a_names = floor("a", "s1") + floor("a", "s2")
    b, b_names = cost("b", "go", "Goes."), floor("b", "go")
    c, c_names = cost("c", "s3", "Third."), floor("c", "s3")
    assert text.startswith("# Skills catalog\n\nGenerated by `scripts/gen-catalog.py` on every sync — do not edit by hand.\n\n"
                           f"## Listing cost\n\n{INTRO}\n\n### Per profile\n\n")
    assert cost_rows(text, "Per profile") == [
        "| Profile | Plugins | Entries | Characters | Names only | First CLI budget | second budget |",
        "|---|---|---|---|---|---|---|",
        f"| `one` | 2 | 2 | {a:,} | {a_names:,} | {round(100 * a / 100)}% of 100 | {round(100 * a / 30)}% of 30 |",
        f"| `two` | 1 | 1 | {b:,} | {b_names:,} | – | {round(100 * b / 30)}% of 30 |",   # "ghost" is no marketplace plugin
        f"| all plugins | 4 | 4 | {a + b + c:,} | {a_names + b_names + c_names:,} | – | – |",   # also `c`, in no profile
    ]
    assert "\nNot measured: `up` (referenced from upstream, its skills are not in this repo).\n" in text
    assert cost_rows(text, "Per plugin") == [
        "| Plugin | Profile | Skills | Commands | Characters | Names only |", "|---|---|---|---|---|---|",
        f"| `a` | one | 2 | 0 | {a:,} | {a_names:,} |",       # the hidden skill is not listed, so it costs nothing
        f"| `c` | – | 1 | 0 | {c:,} | {c_names:,} |",       # most characters first
        f"| `b` | two | 0 | 1 | {b:,} | {b_names:,} |",
        "| `up` | one | – | – | not measured | – |",
    ]


def test_plugins_with_equal_costs_are_sorted_by_name_not_by_marketplace_order(bare_layout):
    r = bare_layout
    r.write_json(".claude-plugin/marketplace.json", {"plugins": [
        {"name": name, "source": f"./plugins/{name}", "description": name} for name in ("pc", "pa", "pb")]})
    for name in ("pc", "pa", "pb"):
        r.write(f"plugins/{name}/skills/s/SKILL.md", "---\nname: s\ndescription: Does it.\n---\n")
    r.gen_catalog()
    rows = cost_rows(r.read("SKILLS.md"), "Per plugin")[2:]
    assert [row.split("|")[1].strip() for row in rows] == ["`pa`", "`pb`", "`pc`"]
    assert len({row.split("|")[5] for row in rows}) == 1     # the same Characters cell: only the name orders them


@pytest.mark.parametrize("profiles_json", ["{not json", "[]", '{"profiles": "x"}', '{"profiles": {"one": "a"}}'])
def test_cost_section_survives_a_missing_or_broken_profiles_json(bare_layout, profiles_json):
    cost_fixture(bare_layout)
    bare_layout.write("profiles.json", profiles_json)
    bare_layout.gen_catalog()
    text = bare_layout.read("SKILLS.md")
    assert "### Per profile" not in text and "Not measured" not in text      # validate.py reports the file itself
    assert cost_rows(text, "Per plugin")[2].startswith("| `a` | – | 2 | 0 |")


def test_cost_columns_follow_the_valid_budgets_only(bare_layout):
    cost_fixture(bare_layout)
    bare_layout.edit_json("profiles.json", lambda d: d["listingBudget"].update(
        broken={"chars": 0, "profiles": ["one"]}, ghost={"chars": 10, "profiles": ["nope"]}))
    bare_layout.gen_catalog()
    head = cost_rows(bare_layout.read("SKILLS.md"), "Per profile")[0]
    assert head == "| Profile | Plugins | Entries | Characters | Names only | First CLI budget | second budget |"
    bare_layout.edit_json("profiles.json", lambda d: d.pop("listingBudget"))
    bare_layout.gen_catalog()
    assert cost_rows(bare_layout.read("SKILLS.md"), "Per profile")[0] == "| Profile | Plugins | Entries | Characters | Names only |"


def test_no_cost_section_without_a_local_plugin(bare_layout):
    bare_layout.write_json(".claude-plugin/marketplace.json", {"plugins": [
        {"name": "up", "source": {"source": "github", "repo": "o/r", "sha": "1" * 40}, "description": "External"}]})
    bare_layout.gen_catalog()
    assert "Listing cost" not in bare_layout.read("SKILLS.md")
    bare_layout.edit_json(".claude-plugin/marketplace.json", lambda d: d["plugins"].append(
        {"name": "loc", "source": "./plugins/loc", "description": "Local"}))
    bare_layout.write("plugins/loc/skills/s/SKILL.md", "---\nname: s\ndescription: Does it.\n---\n")
    bare_layout.gen_catalog()
    assert "## Listing cost\n" in bare_layout.read("SKILLS.md")


def test_the_repo_cost_tables_use_the_helper_the_warnings_use(tmp_path):
    """Smoke test on the real layout, with profiles.json: the table rows are scripts/skill_descriptions.py's numbers."""
    root = tmp_path / "copy"
    shutil.copytree(REPO / "plugins", root / "plugins")
    shutil.copytree(REPO / ".claude-plugin", root / ".claude-plugin")
    shutil.copy2(REPO / "profiles.json", root / "profiles.json")
    (root / "scripts").mkdir()
    for script in ("gen-catalog.py", "skill_descriptions.py"):
        shutil.copy2(REPO / "scripts" / script, root / "scripts" / script)
    res = subprocess.run([sys.executable, str(root / "scripts/gen-catalog.py")], capture_output=True, text=True)
    assert res.returncode == 0, res.stderr
    sys.path.insert(0, str(REPO / "scripts"))
    import skill_descriptions as sd
    prof = json.loads((REPO / "profiles.json").read_text(encoding="utf-8"))
    costs = sd.profile_costs(sd.plugin_costs(sd.listing_entries(REPO)), prof["profiles"])
    rows = cost_rows((root / "SKILLS.md").read_text(encoding="utf-8"), "Per profile")[2:]
    for name, c in costs.items():
        row = next(x for x in rows if x.startswith(f"| `{name}` |"))
        assert f"| {c.entries} | {c.chars:,} | {c.names:,} |" in row
    assert rows[-1].startswith("| all plugins |") and f"| {sum(c.chars for c in costs.values()):,} |" in rows[-1]
