"""scripts/gen-catalog.py: SKILLS.md for a small fixture marketplace, compared byte for byte."""
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

LONG = ("Builds very long descriptions for testing the cut. " * 6).strip()


def build(r) -> None:
    r.write_json(".claude-plugin/marketplace.json", {"name": "fixture", "plugins": [
        {"name": "alpha", "source": "./plugins/alpha", "description": "Alpha: skills, commands and agents."},
        {"name": "beta", "source": "./plugins/beta", "description": "Beta: declared skills only."},
        {"name": "gamma", "source": "./plugins/gamma", "description": "Gamma: a declared path is missing."},
        {"name": "ext", "source": {"source": "url", "url": "https://example.invalid/ext.git", "sha": "0" * 40},
         "description": "External (url)."},
        {"name": "gh", "source": {"source": "github", "repo": "owner/gh-plugin", "sha": "1" * 40},
         "description": "External (github)."},
        {"name": "empty", "source": "./plugins/empty", "description": "Nothing to list."},
    ]})
    # skills: folded, quoted, long, literal block, no frontmatter; listed in path order
    r.write("plugins/alpha/skills/b-folded/SKILL.md",
            "---\nname: b-folded\ndescription: >\n  Folded description\n  over two lines.\nlicense: MIT\n---\nBody.\n")
    r.write("plugins/alpha/skills/a-quoted/SKILL.md",
            "---\nname: 'a-quoted'\ndescription: \"Quoted: keeps the colon.\"\n---\nBody.\n")
    r.write("plugins/alpha/skills/c-long/SKILL.md", f"---\nname: c-long\ndescription: {LONG}\n---\n")
    r.write("plugins/alpha/skills/d-literal/SKILL.md",
            "---\nname: d-literal\ndescription: |-\n  Literal block,\n  joined too.\n---\n")
    r.write("plugins/alpha/skills/e-no-frontmatter/SKILL.md", "# Just a heading\n")
    r.write("plugins/alpha/commands/run.md", "---\ndescription: Runs alpha.\n---\nRun.\n")
    r.write("plugins/alpha/commands/sub/deep.md", "---\ndescription: A nested command.\n---\n")
    r.write("plugins/alpha/agents/reviewer.md",
            "---\nname: code-reviewer\ndescription: Reviews code. Use after a change.\ntools: Read\n---\n")
    # beta: plugin.json lists one skill; the other is left out of the catalog
    r.write_json("plugins/beta/.claude-plugin/plugin.json", {"name": "beta", "skills": ["./skills/listed"]})
    r.write("plugins/beta/skills/listed/SKILL.md", "---\nname: listed\ndescription: Listed.\n---\n")
    r.write("plugins/beta/skills/unlisted/SKILL.md", "---\nname: unlisted\ndescription: Not listed.\n---\n")
    # gamma: a declared skill folder is missing, so every SKILL.md is listed
    r.write_json("plugins/gamma/.claude-plugin/plugin.json", {"name": "gamma", "skills": ["./skills/one", "./skills/gone"]})
    r.write("plugins/gamma/skills/one/SKILL.md", "---\nname: one\ndescription: One.\n---\n")
    r.write("plugins/gamma/skills/two/SKILL.md", "---\nname: two\ndescription: Two.\n---\n")
    (r.root / "plugins/empty").mkdir(parents=True)


EXPECTED = """# Skills catalog

Generated by `scripts/gen-catalog.py` on every sync — do not edit by hand.

## `alpha`

Alpha: skills, commands and agents.

### Skills

| Name | What it does |
|---|---|
| [`a-quoted`](plugins/alpha/skills/a-quoted/SKILL.md) | Quoted: keeps the colon. |
| [`b-folded`](plugins/alpha/skills/b-folded/SKILL.md) | Folded description over two lines. |
| [`c-long`](plugins/alpha/skills/c-long/SKILL.md) | CUT |
| [`d-literal`](plugins/alpha/skills/d-literal/SKILL.md) | Literal block, joined too. |
| [`e-no-frontmatter`](plugins/alpha/skills/e-no-frontmatter/SKILL.md) |  |

### Commands

| Name | What it does |
|---|---|
| [`run`](plugins/alpha/commands/run.md) | Runs alpha. |
| [`deep`](plugins/alpha/commands/sub/deep.md) | A nested command. |

### Agents

| Name | What it does |
|---|---|
| [`code-reviewer`](plugins/alpha/agents/reviewer.md) | Reviews code. Use after a change. |

## `beta`

Beta: declared skills only.

### Skills

| Name | What it does |
|---|---|
| [`listed`](plugins/beta/skills/listed/SKILL.md) | Listed. |

## `gamma`

Gamma: a declared path is missing.

### Skills

| Name | What it does |
|---|---|
| [`one`](plugins/gamma/skills/one/SKILL.md) | One. |
| [`two`](plugins/gamma/skills/two/SKILL.md) | Two. |

## `ext`

External (url).

Referenced from upstream: https://example.invalid/ext.git

## `gh`

External (github).

Referenced from upstream: owner/gh-plugin

## `empty`

Nothing to list.
"""


def expected_cut() -> str:
    """first_sentence(): whitespace collapsed, cut at the last space within 220 characters, plus an ellipsis."""
    cut = LONG[:220]
    return cut[: cut.rfind(" ")] + "…"


def test_catalog_matches_the_expected_markdown(bare_layout):
    build(bare_layout)
    res = bare_layout.gen_catalog()
    assert res.stdout == "==> wrote SKILLS.md (6 plugins)\n"
    assert bare_layout.read("SKILLS.md") == EXPECTED.replace("CUT", expected_cut())


def test_long_description_is_cut_at_a_word_boundary(bare_layout):
    build(bare_layout)
    bare_layout.gen_catalog()
    row = next(x for x in bare_layout.read("SKILLS.md").splitlines() if "c-long" in x)
    text = row.split(" | ", 1)[1].removesuffix(" |")
    assert len(LONG) > 220
    assert text.endswith("…") and len(text) <= 221
    assert LONG.startswith(text[:-1]) and LONG[len(text) - 1] == " "


def test_output_is_deterministic(bare_layout):
    build(bare_layout)
    bare_layout.gen_catalog()
    first = bare_layout.path("SKILLS.md").read_bytes()
    bare_layout.gen_catalog()
    assert bare_layout.path("SKILLS.md").read_bytes() == first
    assert first.endswith(b"\n") and not first.endswith(b"\n\n")


def test_marketplace_order_is_kept(bare_layout):
    build(bare_layout)
    bare_layout.edit_json(".claude-plugin/marketplace.json", lambda d: d["plugins"].reverse())
    bare_layout.gen_catalog()
    headings = [x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("## ")]
    assert headings == ["## `empty`", "## `gh`", "## `ext`", "## `gamma`", "## `beta`", "## `alpha`"]


def test_pipe_in_a_description_does_not_break_the_table(bare_layout):
    bare_layout.write_json(".claude-plugin/marketplace.json",
                           {"plugins": [{"name": "p", "source": "./plugins/p", "description": "P"}]})
    bare_layout.write("plugins/p/skills/s/SKILL.md", "---\nname: s\ndescription: Reads a | b tables.\n---\n")
    bare_layout.gen_catalog()
    row = next(x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("| [`s`]"))
    assert row == "| [`s`](plugins/p/skills/s/SKILL.md) | Reads a \\| b tables. |"


def test_values_are_read_like_validate_py_and_the_evals_read_them(bare_layout):
    """One frontmatter parser (scripts/skill_descriptions.py): an unmatched quote stays, `>+` / `|+` block
    scalars are blocks, keys may hold digits."""
    bare_layout.write_json(".claude-plugin/marketplace.json",
                           {"plugins": [{"name": "p", "source": "./plugins/p", "description": "P"}]})
    bare_layout.write("plugins/p/skills/a/SKILL.md", '---\nname: a\ndescription: Use when you run "make"\n---\n')
    bare_layout.write("plugins/p/skills/b/SKILL.md", "---\nname: b\ndescription: >+\n  Folded, keep.\n---\n")
    bare_layout.write("plugins/p/agents/x.md", "---\nx-y1: 1\nname: agent-x\ndescription: |+\n  Literal.\n---\n")
    bare_layout.gen_catalog()
    rows = [x for x in bare_layout.read("SKILLS.md").splitlines() if x.startswith("| [`")]
    assert rows == ['| [`a`](plugins/p/skills/a/SKILL.md) | Use when you run "make" |',
                    "| [`b`](plugins/p/skills/b/SKILL.md) | Folded, keep. |",
                    "| [`agent-x`](plugins/p/agents/x.md) | Literal. |"]


def test_the_repo_catalog_is_generated_from_the_committed_marketplace(tmp_path):
    """Smoke test on the real layout, copied: gen-catalog.py runs and covers every marketplace plugin."""
    root = tmp_path / "copy"
    shutil.copytree(REPO / "plugins", root / "plugins")
    shutil.copytree(REPO / ".claude-plugin", root / ".claude-plugin")
    (root / "scripts").mkdir()
    for script in ("gen-catalog.py", "skill_descriptions.py"):   # gen-catalog imports the shared parser
        shutil.copy2(REPO / "scripts" / script, root / "scripts" / script)
    res = subprocess.run([sys.executable, str(root / "scripts/gen-catalog.py")], capture_output=True, text=True)
    assert res.returncode == 0, res.stderr
    names = [p["name"] for p in json.loads((root / ".claude-plugin/marketplace.json").read_text())["plugins"]]
    text = (root / "SKILLS.md").read_text(encoding="utf-8")
    for n in names:
        assert f"## `{n}`" in text
