#!/usr/bin/env bats
# scripts/clean-history.sh on a synthetic repository in the test's temp dir (never this checkout).
# Fixture commits are made with git commit-tree, so no commit-msg hook can change their messages.

setup() {
  load helpers
  git filter-repo --version >/dev/null 2>&1 || tool_missing "git filter-repo not installed"
  export GIT_AUTHOR_NAME=fixture GIT_AUTHOR_EMAIL=fixture@example.invalid
  export GIT_COMMITTER_NAME=fixture GIT_COMMITTER_EMAIL=fixture@example.invalid
  S="$BATS_TEST_TMPDIR/src"
  git init -q "$S"
  printf 'hello\n' >"$S/README.md"
  mkdir -p "$S/tests"
  printf 'author: old-me@old.example\n' >"$S/tests/fixture.txt"
  git -C "$S" add -A
  tree=$(git -C "$S" write-tree)
  c1=$(printf 'Initial commit\n' | git -C "$S" commit-tree "$tree")
  c2=$(printf 'Add feature\n\nBody line.\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n' |
    git -C "$S" commit-tree "$tree" -p "$c1")
  c3=$(printf 'Squash merge (#9)\n\n* first part\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n\n---------\n\nCo-authored-by: Me <old-me@old.example>\nCo-authored-by: Friend <friend@example.org>\n' |
    git -C "$S" commit-tree "$tree" -p "$c2")
  c4=$(printf 'Docs\n\nhttps://claude.ai/code/session_0123456789abcdef\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_0123456789abcdef)_\n' |
    GIT_COMMITTER_NAME=Claude GIT_COMMITTER_EMAIL=noreply@anthropic.com git -C "$S" commit-tree "$tree" -p "$c3")
  git -C "$S" update-ref refs/heads/main "$c4"
  git -C "$S" update-ref refs/heads/feature "$c3"
  git -C "$S" symbolic-ref HEAD refs/heads/main
  B="$BATS_TEST_TMPDIR/repo.git"
  git clone -q --bare "file://$S" "$B"
  printf 'old-me@old.example==>me@example.com\n' >"$BATS_TEST_TMPDIR/replace.txt"
}

clean() { run bash "$REPO_ROOT/scripts/clean-history.sh" --owner 'Owner <owner@example.com>' --report-dir "$BATS_TEST_TMPDIR/report" "$@" "$B"; }

@test "clean-history: strips attribution, maps the vendor identity, keeps human co-authors and trees" {
  clean
  assert_status 0
  assert_output_contains "verification passed"
  assert_output_contains "trees changed by --replace-text: 0"
  run bash -c "git -C '$B' log --all --format='%B' | sh '$REPO_ROOT/tools/attribution-guard/attribution-guard.sh' check"
  assert_status 0
  assert_eq "$(git -C "$B" log --all --format='%ce' | sort -u | tr '\n' ' ')" "fixture@example.invalid owner@example.com " "committers"
  assert_eq "$(git -C "$B" rev-list --all | wc -l | tr -d ' ')" 4 "commit count"
  git -C "$B" log -1 --format=%B main~1 | grep -q 'Co-authored-by: Friend <friend@example.org>'
  git -C "$B" log -1 --format=%B main~1 | grep -q '^\* first part$'
  assert_eq "$(git -C "$B" log -1 --format=%B main | sed '/^$/d')" "Docs" "message of the last commit"
  assert_eq "$(wc -l <"$BATS_TEST_TMPDIR/report/attribution-commits.txt" | tr -d ' ')" 3 "commits listed for GitHub Support"
}

@test "clean-history: prints lease-protected push commands and never pushes" {
  clean
  assert_status 0
  assert_output_contains "remote add origin 'file://$S'"
  assert_output_contains "push --force-with-lease='refs/heads/main:"
  assert_eq "$(git -C "$S" log -1 --format=%B main | grep -c 'claude.ai/code')" 2 "source repo untouched"
  refute git -C "$B" remote get-url origin
}

@test "clean-history: --drop-coauthor, --replace-text and --forbid clean an old address everywhere" {
  clean --drop-coauthor old-me@old.example --replace-text "$BATS_TEST_TMPDIR/replace.txt" --forbid old-me@old.example
  assert_status 0
  refute bash -c "git -C '$B' log --all --format=%B | grep -q old-me@old.example"
  assert_eq "$(git -C "$B" show main:tests/fixture.txt)" "author: me@example.com" "file content"
  assert_output_contains "trees changed by --replace-text: 4"
  # the squash message keeps its separator for the remaining co-author, and nothing dangles
  assert_eq "$(git -C "$B" log -1 --format=%B main~1 | sed '/^$/d' | tail -n 2 | tr '\n' '|')" \
    "---------|Co-authored-by: Friend <friend@example.org>|" "end of the squash message"
}

@test "clean-history: a separator left without trailers is removed" {
  only=$(printf 'Squash (#10)\n\n* part\n\n---------\n\nCo-authored-by: Me <old-me@old.example>\n' |
    git -C "$S" commit-tree "$(git -C "$S" write-tree)" -p main)
  git -C "$S" update-ref refs/heads/main "$only"
  rm -rf "$B"; git clone -q --bare "file://$S" "$B"
  clean --drop-coauthor old-me@old.example
  assert_status 0
  assert_eq "$(git -C "$B" log -1 --format=%B main | sed '/^$/d' | tr '\n' '|')" "Squash (#10)|* part|" "message"
}

@test "clean-history: branches deleted in the bare clone first (as in the runbook) are not an obstacle" {
  git -C "$S" update-ref refs/heads/sync/old main~1
  rm -rf "$B"; git clone -q --bare "file://$S" "$B"
  git -C "$B" branch -D sync/old
  clean
  assert_status 0
  assert_eq "$(git -C "$B" for-each-ref --format='%(refname)' refs/heads | tr '\n' ' ')" "refs/heads/feature refs/heads/main " "branches"
}

@test "clean-history: relative --replace-text and --mailmap paths work (filter-repo runs inside the repo)" {
  printf 'Owner <owner@example.com> <fixture@example.invalid>\n' >"$BATS_TEST_TMPDIR/mailmap.txt"
  cd "$BATS_TEST_TMPDIR"
  run bash "$REPO_ROOT/scripts/clean-history.sh" --owner 'Owner <owner@example.com>' --report-dir report \
    --replace-text replace.txt --mailmap mailmap.txt repo.git
  assert_status 0
  assert_eq "$(git -C "$B" show main:tests/fixture.txt)" "author: me@example.com" "file content"
}

@test "clean-history: --forbid fails the verification when the text survives" {
  clean --forbid old-me@old.example
  assert_status 1
  assert_output_contains "'old-me@old.example' still present"
  assert_output_contains "do not push"
}

@test "clean-history: --mailmap maps other old identities" {
  printf 'Owner <owner@example.com> <fixture@example.invalid>\n' >"$BATS_TEST_TMPDIR/mailmap.txt"
  clean --mailmap "$BATS_TEST_TMPDIR/mailmap.txt"
  assert_status 0
  assert_eq "$(git -C "$B" log --all --format='%ae %ce' | sort -u | tr '\n' ' ')" "owner@example.com owner@example.com " "identities"
}

@test "clean-history: attribution in a subject line stops the rewrite" {
  bad=$(printf 'Generated with Claude Code\n' | git -C "$S" commit-tree "$(git -C "$S" write-tree)" -p main)
  git -C "$S" update-ref refs/heads/main "$bad"
  rm -rf "$B"; git clone -q --bare "file://$S" "$B"
  clean
  assert_status 1
  assert_output_contains "nothing was pushed"
}

@test "clean-history: --help and a usage error print the header comment and no code" {
  run bash "$REPO_ROOT/scripts/clean-history.sh" --help
  assert_status 0
  assert_output_contains "clean-history.sh --owner 'Name <email>' [options] BARE_REPO"
  assert_output_contains "2 usage."
  refute_output_contains "set -euo pipefail"
  run bash "$REPO_ROOT/scripts/clean-history.sh" --bogus
  assert_status 2
  assert_line "clean-history: unknown option: --bogus"
  refute_output_contains "set -euo pipefail"
}

@test "clean-history: refuses a non-bare repository, a mirror with refs/pull and a bad --owner" {
  run bash "$REPO_ROOT/scripts/clean-history.sh" --owner 'Owner <owner@example.com>' "$S"
  assert_status 1
  assert_output_contains "not a bare repository"
  git -C "$B" update-ref refs/pull/1/head main
  clean
  assert_status 1
  assert_output_contains "refs/pull"
  run bash "$REPO_ROOT/scripts/clean-history.sh" --owner 'no address' "$B"
  assert_status 2
  run bash "$REPO_ROOT/scripts/clean-history.sh" --owner 'Claude <noreply@anthropic.com>' "$B"
  assert_status 2
}
