#!/bin/sh
# Tests for the attribution guard. Usage: sh tools/attribution-guard/tests/run-tests.sh [path-to-git]
# Runs in a throwaway HOME; never touches the real git config.
# ok/ko never fail, so `test && ok || ko` is a safe if/else here; GIT_EDITOR is expanded by git's sh.
# shellcheck disable=SC2015,SC2016
set -u
GIT=${1:-git}
S=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
W=$(mktemp -d)
trap 'rm -rf "$W"' EXIT
export HOME="$W/home" GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL="$W/home/.gitconfig"
unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL CLAUDE_ENV_FILE CLAUDE_PROJECT_DIR ATTRIB_RE
mkdir -p "$HOME"
git() { command "$GIT" "$@"; }
pass=0 fail=0
ok() { pass=$((pass + 1)); printf 'ok   %s\n' "$*"; }
ko() { fail=$((fail + 1)); printf 'FAIL %s\n' "$*"; }
G="$S/attribution-guard.sh"

git config --global user.name 'Lucas'
git config --global user.email '73317412+lucas4790@users.noreply.github.com'
git config --global init.defaultBranch main
git config --global commit.gpgsign false

# ---- installer (Git < 2.54 path: global core.hooksPath dispatcher; >= 2.54: config hooks)
sh "$S/install.sh" >/dev/null 2>"$W/err" && ok "install.sh ran" || ko "install.sh failed: $(cat "$W/err")"
H="$HOME/.config/git/attribution-guard"
[ -f "$H/patterns.ere" ] && [ -f "$H/attribution-guard.sh" ] && ok "installed files present" || ko "installed files missing"

git init -q --bare "$W/remote.git"
git init -q "$W/repo"
cd "$W/repo" || exit 1
git remote add origin "$W/remote.git"
echo base >f && git add f && git commit -q -m 'Initial commit' && git push -q origin main

n=0
commit_with() { # message in $W/msg; prints resulting message or FAILED
    n=$((n + 1)); echo "$n" >>f; git add f
    if git commit -q -F "$W/msg" 2>"$W/err"; then git log -1 --format=%B; else echo FAILED; fi
}

# ---- legit messages must pass unchanged (both modes); the word "claude" alone never matches
for mode in strip reject; do
  git config attributionguard.mode "$mode"
  while IFS= read -r m; do
    printf '%s\n' "$m" | sed 's/\\n/\n/g' >"$W/msg"
    out=$(commit_with)
    exp=$(git stripspace <"$W/msg")
    if [ "$out" = "$exp" ]; then ok "[$mode] legit passes: $m"; else ko "[$mode] legit changed/blocked: $m -> $out $(cat "$W/err")"; fi
  done <<'EOF'
Add claude-security plugin
Update .claude-plugin/marketplace.json for claude-code-setup
chore: sync high-trust upstream skills (anthropics-skills@3337550, claude-plugins-official@fa59bc9)
Document Claude Code cloud sessions (claude.ai/code) in README
Generate SKILLS.md with gen-catalog.py\n\nGenerated with scripts/gen-catalog.py; see https://code.claude.com/docs/en/plugins
Refresh SKILLS.md generated by claude-plugins-official sync
Drop files generated with claude-code-setup
Fix Claude Code manifest validation\n\nReviewed-by: Lucas (claude-security maintainer)\nCo-authored-by: Lucas <lucas@example.com>
Explain how the guard handles attribution trailers\n\nThe hook strips trailers that name the model as co-author.
EOF
done

# ---- attribution: strip mode removes lines, reject mode blocks
cat >"$W/cases" <<'EOF'
Add guardrails\n\nBody text.\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_0123456789abcdefghijklmn
Add guardrails\n\nBody.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_0123456789abcdefghijklmn\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_0123456789abcdefghijklmn)_
Add guardrails\n\nco-authored-by: claude <noreply@anthropic.com>
Add guardrails\n\nAssisted-by: Claude Code
Add guardrails\n\nSigned-off-by: Lucas <l@x.nl>\nCo-developed-by: Anthropic Claude
Add guardrails\n\nSee the chat: https://claude.ai/share/abc-123
Add guardrails\n\nBuilt with [Claude Code](https://claude.com/claude-code)
Add guardrails\n\nWritten by Claude Code
Add guardrails\n\nAssisted by Claude
Add guardrails\n\nOpen https://claude.ai/code/artifact/0b1c2d3e
EOF
git config attributionguard.mode strip
while IFS= read -r m; do
  printf '%s\n' "$m" | sed 's/\\n/\n/g' >"$W/msg"
  out=$(commit_with)
  if [ "$out" != FAILED ] && printf '%s\n' "$out" | sh "$G" check >/dev/null \
     && printf '%s\n' "$out" | head -n 1 | grep -qx 'Add guardrails'; then
    ok "[strip] cleaned: $(printf '%s' "$out" | tr '\n' '|')"
  else ko "[strip] not cleaned: $m -> $out"; fi
done <"$W/cases"
printf 'Add guardrails\n\nSigned-off-by: Lucas <l@x.nl>\nCo-developed-by: Anthropic Claude\n' >"$W/msg"
out=$(commit_with); printf '%s\n' "$out" | grep -q 'Signed-off-by: Lucas' && ok "[strip] keeps human Signed-off-by" || ko "[strip] lost Signed-off-by: $out"

git config attributionguard.mode reject
while IFS= read -r m; do
  printf '%s\n' "$m" | sed 's/\\n/\n/g' >"$W/msg"
  out=$(commit_with)
  if [ "$out" = FAILED ]; then ok "[reject] blocked: $(head -c 60 "$W/msg" | tr '\n' '|')"; else ko "[reject] allowed: $m"; fi
done <"$W/cases"
git reset -q --hard HEAD; git config attributionguard.mode strip

printf 'Co-Authored-By: Claude <noreply@anthropic.com>\n' >"$W/msg"
[ "$(commit_with)" = FAILED ] && ok "[strip] subject-line hit rejected" || ko "[strip] subject-line hit accepted"
git reset -q --hard HEAD

# ---- identity: vendor author always rejected; vendor committer only with checkCommitter=true
printf 'Clean message\n' >"$W/msg"
out=$(GIT_AUTHOR_NAME=Claude GIT_AUTHOR_EMAIL=noreply@anthropic.com commit_with)
[ "$out" = FAILED ] && ok "vendor author rejected" || ko "vendor author accepted"
git reset -q --hard HEAD
git config attributionguard.checkCommitter false
out=$(GIT_COMMITTER_NAME=Claude GIT_COMMITTER_EMAIL=noreply@anthropic.com commit_with)
[ "$out" != FAILED ] && ok "vendor committer allowed with checkCommitter=false (cloud)" || ko "vendor committer rejected with checkCommitter=false"
git reset -q --hard HEAD~1
git config attributionguard.checkCommitter true
out=$(GIT_COMMITTER_NAME=Claude GIT_COMMITTER_EMAIL=noreply@anthropic.com commit_with)
[ "$out" = FAILED ] && ok "vendor committer rejected with checkCommitter=true (local)" || ko "vendor committer accepted with checkCommitter=true"
git reset -q --hard HEAD

# ---- git commit -m, --amend, merge, commit -v with a diff that contains patterns
echo x >>f; git add f
git commit -q -m 'Use -m' -m 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>' 2>/dev/null
git log -1 --format=%B | sh "$G" check >/dev/null && ok "commit -m stripped" || ko "commit -m kept trailer"
git commit -q --amend -m 'Amended' -m 'Claude-Session: https://claude.ai/code/session_x' 2>/dev/null
git log -1 --format=%B | sh "$G" check >/dev/null && ok "commit --amend stripped" || ko "amend kept trailer"
printf 'Co-Authored-By: Claude <noreply@anthropic.com>\n' >pattern-doc.txt; git add pattern-doc.txt
GIT_EDITOR='sh -c "printf \"Add pattern doc\\n\" | cat - \"\$1\" > \"\$1.t\" && mv \"\$1.t\" \"\$1\"" --' git commit -q -v 2>"$W/err" \
  && [ "$(git log -1 --format=%s)" = 'Add pattern doc' ] && ok "commit -v: diff below scissors ignored" || ko "commit -v blocked: $(cat "$W/err")"
git checkout -q -b feature; echo feat >g; git add g; git commit -q -m 'Feature'
git checkout -q main; echo m >>f; git add f; git commit -q -m 'Main change'
git merge -q --no-ff feature -m 'Merge feature' -m 'Co-Authored-By: Claude <noreply@anthropic.com>' 2>/dev/null
git log -1 --format=%B | sh "$G" check >/dev/null && ok "git merge message stripped" || ko "merge kept trailer"

# ---- pre-push blocks what commit-msg missed (--no-verify)
git checkout -q -b sneaky; echo s >h; git add h
git commit -q --no-verify -m 'Sneaky' -m 'Co-Authored-By: Claude <noreply@anthropic.com>'
if git push -q origin sneaky 2>"$W/err"; then ko "pre-push allowed --no-verify commit"; else grep -q 'refusing to push' "$W/err" && ok "pre-push blocked --no-verify commit" || ko "push failed otherwise: $(cat "$W/err")"; fi
git checkout -q main
git push -q origin main 2>"$W/err" && ok "pre-push allows clean main" || ko "clean push blocked: $(cat "$W/err")"
git checkout -q -b vendor-author main; echo c >i; git add i
GIT_AUTHOR_NAME=Claude GIT_AUTHOR_EMAIL=noreply@anthropic.com git commit -q --no-verify -m 'Add file i'
git push -q origin vendor-author 2>"$W/err" && ko "pre-push allowed vendor-authored commit" || ok "pre-push blocked vendor-authored commit"
git checkout -q sneaky; git rebase -q -r --exec 'git commit -q --amend --no-edit --reset-author' main 2>/dev/null
git push -q origin sneaky 2>"$W/err" && ok "fix recipe (rebase --exec amend --reset-author) cleans and push passes" || ko "fix recipe failed: $(cat "$W/err")"
git checkout -q main

# ---- repo hooks (.githooks wrappers used by this repository)
mkdir -p "$W/r2/.githooks" "$W/r2/tools/attribution-guard"
cp "$S/attribution-guard.sh" "$S/patterns.ere" "$W/r2/tools/attribution-guard/"
cp "$S/../../.githooks/commit-msg" "$S/../../.githooks/pre-push" "$W/r2/.githooks/" 2>/dev/null
cd "$W/r2" && git init -q && git config core.hooksPath .githooks && git config --global --unset core.hooksPath 2>/dev/null
for k in $(git config --global --name-only --get-regexp '^hook\.' 2>/dev/null); do git config --global --unset "$k"; done
echo a >a; git add a; git commit -q -m 'Repo hook' -m 'Claude-Session: https://claude.ai/code/session_y' 2>/dev/null
git log -1 --format=%B | sh "$G" check >/dev/null && ok ".githooks/commit-msg strips" || ko ".githooks/commit-msg did not strip"
cd "$W/repo" || exit 1

# ---- Claude Code PreToolUse hook
P="$S/claude-pretooluse.sh"
pt() { printf '%s' "$1" | sh "$P" >/dev/null 2>&1; echo $?; }
[ "$(pt '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"Fix\" -m \"Co-Authored-By: Claude <noreply@anthropic.com>\""}}')" = 2 ] && ok "pretooluse blocks git commit with trailer" || ko "pretooluse allowed git commit with trailer"
[ "$(pt '{"tool_name":"Bash","tool_input":{"command":"git commit -m \"Add claude-security plugin\""}}')" = 0 ] && ok "pretooluse allows clean commit" || ko "pretooluse blocked clean commit"
[ "$(pt '{"tool_name":"Bash","tool_input":{"command":"grep -rn noreply@anthropic.com ."}}')" = 0 ] && ok "pretooluse ignores non-publishing commands" || ko "pretooluse blocked a grep"
[ "$(pt '{"tool_name":"mcp__github__create_pull_request","tool_input":{"title":"x","body":"Summary\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"}}')" = 2 ] && ok "pretooluse blocks MCP PR body with footer" || ko "pretooluse allowed MCP PR footer"
[ "$(pt '{"tool_name":"mcp__github__merge_pull_request","tool_input":{"commit_message":"x\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>"}}')" = 2 ] && ok "pretooluse blocks MCP merge message with trailer" || ko "pretooluse allowed MCP merge trailer"
[ "$(pt '{"tool_name":"PowerShell","tool_input":{"command":"gh pr create --body \"https://claude.ai/code/session_abc\""}}')" = 2 ] && ok "pretooluse blocks PowerShell gh pr with session link" || ko "pretooluse allowed PowerShell session link"
[ "$(pt '{"tool_name":"Bash","tool_input":{"command":"az repos pr create --title \"Fix\" --description \"Summary\n\nGenerated with [Claude Code](https://claude.com/claude-code)\""}}')" = 2 ] && ok "pretooluse blocks az repos pr create with footer" || ko "pretooluse allowed az repos pr footer"
[ "$(pt '{"tool_name":"Bash","tool_input":{"command":"az repos pr create --title \"Add claude-security plugin\" --description \"Adds the plugin\""}}')" = 0 ] && ok "pretooluse allows clean az repos pr create" || ko "pretooluse blocked clean az repos pr"
[ "$(pt '{"tool_name":"PowerShell","tool_input":{"command":"Invoke-RestMethod -Method Patch https://dev.azure.com/org/p/_apis/git/repositories/r/pullrequests/7 -Body (@{description=\"Claude-Session: https://claude.ai/code/session_x\"} | ConvertTo-Json)"}}')" = 2 ] && ok "pretooluse blocks REST call to dev.azure.com with session link" || ko "pretooluse allowed ADO REST session link"
[ "$(pt '{"tool_name":"mcp__ado__repo_create_pull_request","tool_input":{"title":"Fix","description":"Body\n\nCo-Authored-By: Claude <noreply@anthropic.com>"}}')" = 2 ] && ok "pretooluse blocks Azure DevOps MCP PR with trailer" || ko "pretooluse allowed ADO MCP trailer"

# ---- SessionStart hook
mkdir -p "$W/r3/.githooks" "$W/r3/tools/attribution-guard"
cp "$S/session-start.sh" "$W/r3/tools/attribution-guard/"
printf 'lucas4790 <73317412+lucas4790@users.noreply.github.com>\n' >"$W/r3/tools/attribution-guard/cloud-author"
cd "$W/r3" && git init -q
git config user.email noreply@anthropic.com
CLAUDE_PROJECT_DIR="$W/r3" CLAUDE_ENV_FILE="$W/envfile" sh tools/attribution-guard/session-start.sh
[ "$(git config --get core.hooksPath)" = .githooks ] && ok "session-start sets core.hooksPath" || ko "session-start did not set core.hooksPath"
grep -q "GIT_AUTHOR_EMAIL='73317412+lucas4790@users.noreply.github.com'" "$W/envfile" 2>/dev/null && ok "session-start sets owner author in cloud identity" || ko "session-start author env missing"
rm -f "$W/envfile"; git config user.email me@example.com
CLAUDE_PROJECT_DIR="$W/r3" CLAUDE_ENV_FILE="$W/envfile" sh tools/attribution-guard/session-start.sh
[ ! -s "$W/envfile" ] && ok "session-start leaves a normal identity alone" || ko "session-start overrode a normal identity"
cd "$W/repo" || exit 1

printf '\n%s passed, %s failed (git %s, sh=%s)\n' "$pass" "$fail" "$(git version | cut -d' ' -f3)" "$(readlink -f /bin/sh 2>/dev/null || echo sh)"
[ "$fail" -eq 0 ]
