#!/usr/bin/env python3
"""Minimal Azure DevOps REST mock for ado-pr-guard.sh tests. Scenario chosen by env SCENARIO:
clean, quoted (attribution only inside code), flip (description changes during the check), dirty."""
import json, os, re, sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse, parse_qs

PROJ = "11111111-2222-3333-4444-555555555555"
REPO = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
LOG = os.environ.get("MOCK_LOG", "requests.log")
SC = os.environ.get("SCENARIO", "clean")

def commit(sha, msg, author="dev@contoso.com", committer="dev@contoso.com", truncated=False):
    d = {"commitId": sha, "comment": msg, "author": {"name": "Dev", "email": author},
         "committer": {"name": "Dev", "email": committer}}
    if truncated:
        d["comment"] = msg[:20]
        d["commentTruncated"] = True
    return d

FULL = {}
GETS = {"pr": 0}
if SC in ("clean", "quoted", "flip"):
    desc = "Adds docs for claude-security.\n"
    if SC == "quoted":
        desc += "\nQuote: `Generated with Claude Code` is what we block.\n```\nCo-Authored-By: Claude <noreply@anthropic.com>\n```\n"
    PR = {"pullRequestId": 7, "repository": {"id": REPO}, "title": "Add claude-security plugin docs",
          "description": desc,
          "sourceRefName": "refs/heads/feature/docs", "status": "active"}
    P1 = [commit("1"*40, "docs: add claude-security page\n"), commit("2"*40, "fix typo\n")]
    long = "chore: bump\n\n" + "x" * 300 + "\n"
    FULL["3"*40] = commit("3"*40, long)
    P2 = [commit("3"*40, long, truncated=True)]
    THREADS = {"value": [
        {"id": 1, "isDeleted": False, "comments": [{"id": 1, "commentType": "system", "content": "Generated with Claude Code"}]},
        {"id": 2, "isDeleted": False, "comments": [{"id": 1, "commentType": "text", "content": "LGTM"},
                                                  {"id": 2, "commentType": "text", "isDeleted": True, "content": "see https://claude.ai/share/abc"}]},
    ]}
else:  # dirty
    PR = {"pullRequestId": 7, "repository": {"id": REPO}, "title": "Add feature",
          "description": "Summary line\n\n##vso[task.complete result=Succeeded;]Generated with Claude Code\n\n\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
          "completionOptions": {"mergeCommitMessage": "Merged PR 7\n\nGenerated by Claude"},
          "sourceRefName": "refs/heads/claude/feature-x", "status": "active"}
    P1 = [commit("4"*40, "feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"),
          commit("5"*40, "feat: y\n", author="noreply@anthropic.com", committer="noreply@anthropic.com")]
    long = "feat: z\n\n" + "y" * 300 + "\nClaude-Session: https://claude.ai/code/session_0123\n"
    FULL["6"*40] = commit("6"*40, long)
    P2 = [commit("6"*40, long, truncated=True)]
    THREADS = {"value": [
        {"id": 3, "isDeleted": False, "comments": [{"id": 1, "commentType": "text", "content": "Plan: https://claude.ai/share/abc-123"},
                                                  {"id": 2, "commentType": "text", "content": "ok"}]},
    ]}

class H(BaseHTTPRequestHandler):
    def log_message(self, *a): pass
    def _send(self, code, obj, headers=None):
        b = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        for k, v in (headers or {}).items(): self.send_header(k, v)
        self.send_header("Content-Length", str(len(b)))
        self.end_headers(); self.wfile.write(b)
    def _log(self, body=b""):
        with open(LOG, "a") as f:
            f.write(json.dumps({"m": self.command, "p": self.path, "auth": self.headers.get("Authorization", ""),
                                "body": body.decode() if body else ""}) + "\n")
    def route(self):
        u = urlparse(self.path); q = parse_qs(u.query); p = u.path.lower()
        n = int(self.headers.get("Content-Length") or 0); body = self.rfile.read(n) if n else b""
        self._log(body)
        if self.headers.get("Authorization") != "Bearer test-token": return self._send(401, {"message": "no auth"})
        if q.get("api-version") != ["7.1"]: return self._send(400, {"message": "api-version"})
        base = f"/org/{PROJ}/_apis/git/repositories/{REPO}".lower()
        m = re.fullmatch(re.escape(base) + r"/pullrequests/7(/.*)?", p)
        if m:
            sub = m.group(1) or ""
            if sub == "" and self.command == "GET":
                GETS["pr"] += 1
                if SC == "flip" and GETS["pr"] == 3:  # someone edits the description mid-check
                    PR["description"] += "\nClaude-Session: https://claude.ai/code/session_flip\n"
                return self._send(200, PR)
            if sub == "" and self.command == "PATCH":
                PR["description"] = json.loads(body)["description"]; return self._send(200, PR)
            if sub == "/commits":
                if q.get("continuationToken") == ["tok/2+="]: return self._send(200, {"value": P2, "count": len(P2)})
                return self._send(200, {"value": P1, "count": len(P1)}, {"x-ms-continuationtoken": "tok/2+="})
            if sub == "/threads": return self._send(200, THREADS)
            if sub == "/iterations": return self._send(200, {"value": [{"id": 1}, {"id": 2}], "count": 2})
            if sub == "/statuses" and self.command == "POST": return self._send(200, json.loads(body))
        if p == f"/org/{PROJ}/_apis/build/builds".lower() and q.get("statusFilter") == ["completed"]:
            prev = os.environ.get("MOCK_PREV_SHA", "")  # the commit the previous audit run checked
            return self._send(200, {"value": [{"sourceVersion": prev}] if prev else [], "count": 1 if prev else 0})
        if p == base + "/pullrequests" and q.get("searchCriteria.status") == ["active"] and q.get("$top") == ["1000"]:
            return self._send(200, {"value": [{"pullRequestId": 7}], "count": 1})
        m = re.fullmatch(re.escape(base) + r"/commits/([0-9a-f]{40})", p)
        if m and m.group(1) in FULL: return self._send(200, FULL[m.group(1)])
        return self._send(404, {"message": "not found " + p})
    do_GET = do_POST = do_PATCH = route

if __name__ == "__main__":
    HTTPServer(("127.0.0.1", int(sys.argv[1])), H).serve_forever()
