#!/usr/bin/env python3
"""Generates SKILLS.md from the marketplace manifest and each plugin's skills, commands and agents."""
import json
import sys
from pathlib import Path

# No scripts/__pycache__: the sync job runs this script and then `git add -A`.
sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
# the same frontmatter parser and skill list as validate.py and the eval index
from skill_descriptions import parse_frontmatter, skill_files  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE = json.loads((ROOT / ".claude-plugin/marketplace.json").read_text(encoding="utf-8"))


def frontmatter(path: Path) -> dict:
    return parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))


def first_sentence(text: str, limit: int = 220) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    return cut[: cut.rfind(" ")] + "…"


def collect(plugin_dir: Path, kind: str, pattern: str):
    items = []
    files = skill_files(plugin_dir) if kind == "skills" else sorted(plugin_dir.rglob(pattern))
    for f in files:
        fm = frontmatter(f)
        name = fm.get("name") or (f.parent.name if kind == "skills" else f.stem)
        desc = fm.get("description", "")
        items.append((name, first_sentence(desc), f.relative_to(ROOT).as_posix()))
    return items


out = ["# Skills catalog", "",
       "Generated by `scripts/gen-catalog.py` on every sync — do not edit by hand.", ""]

for p in MARKETPLACE["plugins"]:
    name, desc = p["name"], p.get("description", "")
    out += [f"## `{name}`", "", desc, ""]
    if isinstance(p["source"], dict):
        out += [f"Referenced from upstream: {p['source'].get('url') or p['source'].get('repo')}", ""]
        continue
    pdir = ROOT / p["source"]
    sections = [
        ("Skills", collect(pdir, "skills", "SKILL.md")),
        ("Commands", collect(pdir / "commands", "commands", "*.md") if (pdir / "commands").is_dir() else []),
        ("Agents", collect(pdir / "agents", "agents", "*.md") if (pdir / "agents").is_dir() else []),
    ]
    for title, items in sections:
        if not items:
            continue
        out += [f"### {title}", "", "| Name | What it does |", "|---|---|"]
        for n, d, rel in items:
            d = d.replace("|", "\\|")  # a bare | would end the table cell
            out.append(f"| [`{n}`]({rel}) | {d} |")
        out.append("")

(ROOT / "SKILLS.md").write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
print(f"==> wrote SKILLS.md ({len(MARKETPLACE['plugins'])} plugins)")
