#!/usr/bin/env python3
"""Generates SKILLS.md from the marketplace manifest and each plugin's skills, commands and agents."""
import json
import sys
from pathlib import Path

# No scripts/__pycache__: the sync job runs this script and then `git add -A`.
sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
# the same frontmatter parser, skill list and listing cost as validate.py and the eval index
from skill_descriptions import (Cost, load_profiles, parse_budgets, parse_frontmatter, plugin_costs,  # noqa: E402
                                plugin_entries, profile_costs, profile_members, skill_files)

ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE = json.loads((ROOT / ".claude-plugin/marketplace.json").read_text(encoding="utf-8"))


def frontmatter(path: Path) -> dict:
    return parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))


def first_sentence(text: str, limit: int = 220) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    return cut[: cut.rfind(" ")] + "…"


def collect(plugin_dir: Path, kind: str, pattern: str):
    items = []
    files = skill_files(plugin_dir) if kind == "skills" else sorted(plugin_dir.rglob(pattern))
    for f in files:
        fm = frontmatter(f)
        name = fm.get("name") or (f.parent.name if kind == "skills" else f.stem)
        desc = fm.get("description", "")
        items.append((name, first_sentence(desc), f.relative_to(ROOT).as_posix()))
    return items


def cost_section() -> list[str]:
    """The "Listing cost" tables: what each profile and plugin adds to the skill listing (README, Listing budget)."""
    local = [p for p in MARKETPLACE["plugins"] if isinstance(p["source"], str)]
    costs = plugin_costs([e for p in local for e in plugin_entries(ROOT / p["source"], p["name"], ROOT)])
    external = [p["name"] for p in MARKETPLACE["plugins"] if isinstance(p["source"], dict)]
    listed = {p["name"] for p in MARKETPLACE["plugins"]}
    prof = load_profiles(ROOT)
    profiles = profile_members(prof)
    budgets = parse_budgets(prof)[0]
    home = {m: name for name, members in profiles.items() for m in members}
    n = lambda v: f"{v:,}"  # noqa: E731
    out = ["## Listing cost", "",
           "Claude Code puts one line per skill and command (`- plugin:name: description`) into the model's context in "
           "every session. These tables count those characters, including the line break after each entry "
           "(`README.md`, \"Listing budget\"). Copilot CLI is assumed to list the same way: its format and what it does "
           "over its budget are not verified, so its column uses the same count. Skills with "
           "`disable-model-invocation: true` are not listed and agents are not part of it. \"Names only\" is what "
           "stays when a client drops every description.", ""]
    if profiles:
        head = ["Profile", "Plugins", "Entries", "Characters", "Names only"] + [f"{b.label} budget" for b in budgets]
        out += ["### Per profile", "", "| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        by_profile = profile_costs(costs, profiles)
        for name, c in by_profile.items():
            cells = [f"`{name}`", str(sum(m in listed for m in profiles[name])), str(c.entries), n(c.chars), n(c.names)]
            cells += [f"{round(100 * c.chars / b.chars)}% of {n(b.chars)}" if name in b.profiles else "–" for b in budgets]
            out.append("| " + " | ".join(cells) + " |")
        total = sum(costs.values(), Cost())   # every plugin, also one that is in no profile (validate.py reports that)
        out.append("| all plugins | " + " | ".join([str(len(listed)), str(total.entries), n(total.chars), n(total.names)]
                                                  + ["–"] * len(budgets)) + " |")
        out.append("")
        skipped = [x for x in external if x in home]
        if skipped:
            out += ["Not measured: " + ", ".join(f"`{x}`" for x in skipped)
                    + " (referenced from upstream, its skills are not in this repo).", ""]
    rows = sorted(((p["name"], costs.get(p["name"], Cost())) for p in local), key=lambda r: (-r[1].chars, r[0]))
    out += ["### Per plugin", "", "| Plugin | Profile | Skills | Commands | Characters | Names only |", "|---|---|---|---|---|---|"]
    for name, c in rows:
        out.append(f"| `{name}` | {home.get(name, '–')} | {c.skills} | {c.commands} | {n(c.chars)} | {n(c.names)} |")
    out += [f"| `{x}` | {home.get(x, '–')} | – | – | not measured | – |" for x in external]
    return out + [""]


out = ["# Skills catalog", "",
       "Generated by `scripts/gen-catalog.py` on every sync — do not edit by hand.", ""]
if any(isinstance(p["source"], str) for p in MARKETPLACE["plugins"]):
    out += cost_section()

for p in MARKETPLACE["plugins"]:
    name, desc = p["name"], p.get("description", "")
    out += [f"## `{name}`", "", desc, ""]
    if isinstance(p["source"], dict):
        out += [f"Referenced from upstream: {p['source'].get('url') or p['source'].get('repo')}", ""]
        continue
    pdir = ROOT / p["source"]
    sections = [
        ("Skills", collect(pdir, "skills", "SKILL.md")),
        ("Commands", collect(pdir / "commands", "commands", "*.md") if (pdir / "commands").is_dir() else []),
        ("Agents", collect(pdir / "agents", "agents", "*.md") if (pdir / "agents").is_dir() else []),
    ]
    for title, items in sections:
        if not items:
            continue
        out += [f"### {title}", "", "| Name | What it does |", "|---|---|"]
        for n, d, rel in items:
            d = d.replace("|", "\\|")  # a bare | would end the table cell
            out.append(f"| [`{n}`]({rel}) | {d} |")
        out.append("")

(ROOT / "SKILLS.md").write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
print(f"==> wrote SKILLS.md ({len(MARKETPLACE['plugins'])} plugins)")
