#!/usr/bin/env python3
"""Generates SKILLS.md from the marketplace manifest and each plugin's skills, commands and agents."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE = json.loads((ROOT / ".claude-plugin/marketplace.json").read_text())


def frontmatter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    if not m:
        return {}
    data, key, buf, folded = {}, None, [], False
    for line in m.group(1).splitlines():
        if key and (line.startswith(" ") or line.startswith("\t")):
            buf.append(line.strip())
            continue
        if key:
            data[key] = (" " if folded else "\n").join(buf).strip()
        km = re.match(r"^([A-Za-z_-]+):\s*(.*)$", line)
        if not km:
            key = None
            continue
        key, val = km.group(1), km.group(2).strip()
        folded = val in (">", ">-", "|", "|-")
        buf = [] if folded else [val.strip("'\"")]
    if key:
        data[key] = (" " if folded else "\n").join(buf).strip()
    return data


def first_sentence(text: str, limit: int = 220) -> str:
    text = " ".join(text.split())
    if len(text) <= limit:
        return text
    cut = text[:limit]
    return cut[: cut.rfind(" ")] + "…"


def collect(plugin_dir: Path, kind: str, pattern: str):
    items = []
    for f in sorted(plugin_dir.rglob(pattern)):
        if kind == "skills" and f.name != "SKILL.md":
            continue
        fm = frontmatter(f)
        name = fm.get("name") or (f.parent.name if kind == "skills" else f.stem)
        desc = fm.get("description", "")
        items.append((name, first_sentence(desc), f.relative_to(ROOT).as_posix()))
    return items


out = ["# Skills catalog", "",
       "Generated by `scripts/gen-catalog.py` on every sync — do not edit by hand.", ""]

for p in MARKETPLACE["plugins"]:
    name, desc = p["name"], p.get("description", "")
    out += [f"## `{name}`", "", desc, ""]
    if isinstance(p["source"], dict):
        out += [f"Referenced from upstream: {p['source'].get('url') or p['source'].get('repo')}", ""]
        continue
    pdir = ROOT / p["source"]
    sections = [
        ("Skills", collect(pdir, "skills", "SKILL.md")),
        ("Commands", collect(pdir / "commands", "commands", "*.md") if (pdir / "commands").is_dir() else []),
        ("Agents", collect(pdir / "agents", "agents", "*.md") if (pdir / "agents").is_dir() else []),
    ]
    for title, items in sections:
        if not items:
            continue
        out += [f"### {title}", "", "| Name | What it does |", "|---|---|"]
        for n, d, rel in items:
            out.append(f"| [`{n}`]({rel}) | {d} |")
        out.append("")

(ROOT / "SKILLS.md").write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
print(f"==> wrote SKILLS.md ({len(MARKETPLACE['plugins'])} plugins)")
